services:
    app:
        container_name: booking.app
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PORT=${PORT}
        ports:
            - '3001:3000'
        depends_on:
            - database
        volumes:
            - ./src:/app/src
    database:
        container_name: booking.database
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "3307:3306"
        volumes:
            - ./database:/docker-entrypoint-initdb.d